/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tourguidesl;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form clientRegister
     */
    public ClientForm() {
        initComponents();
        RefreshRecordTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_group_gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        text_field_email = new java.awt.TextField();
        radio_button_male = new javax.swing.JRadioButton();
        radio_button_female = new javax.swing.JRadioButton();
        text_field_contact = new java.awt.TextField();
        label_contact = new javax.swing.JLabel();
        radio_button_other = new javax.swing.JRadioButton();
        label_name = new javax.swing.JLabel();
        label_age = new javax.swing.JLabel();
        label_country = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_gender = new javax.swing.JLabel();
        text_field_name = new java.awt.TextField();
        text_field_age = new java.awt.TextField();
        text_field_country = new java.awt.TextField();
        button_clear = new javax.swing.JButton();
        button_register = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        label_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_records = new javax.swing.JTable();
        button_refresh = new javax.swing.JButton();
        button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(text_field_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 241, 30));

        button_group_gender.add(radio_button_male);
        radio_button_male.setForeground(new java.awt.Color(255, 255, 255));
        radio_button_male.setText("Male");
        radio_button_male.setActionCommand("MALE");
        jPanel1.add(radio_button_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 310, 60, -1));

        button_group_gender.add(radio_button_female);
        radio_button_female.setForeground(new java.awt.Color(255, 255, 255));
        radio_button_female.setText("Female");
        radio_button_female.setActionCommand("FEMALE");
        jPanel1.add(radio_button_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 80, -1));
        jPanel1.add(text_field_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 241, 30));

        label_contact.setBackground(new java.awt.Color(255, 255, 255));
        label_contact.setForeground(new java.awt.Color(255, 255, 255));
        label_contact.setText("Contact");
        jPanel1.add(label_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        button_group_gender.add(radio_button_other);
        radio_button_other.setForeground(new java.awt.Color(255, 255, 255));
        radio_button_other.setText("Prefer not to tell");
        radio_button_other.setActionCommand("UNKOWN");
        jPanel1.add(radio_button_other, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("Name");
        jPanel1.add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 41, 20));

        label_age.setForeground(new java.awt.Color(255, 255, 255));
        label_age.setText("Age");
        jPanel1.add(label_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 41, 20));

        label_country.setForeground(new java.awt.Color(255, 255, 255));
        label_country.setText("Country");
        jPanel1.add(label_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        label_email.setForeground(new java.awt.Color(255, 255, 255));
        label_email.setText("Email");
        jPanel1.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 41, 20));

        label_gender.setForeground(new java.awt.Color(255, 255, 255));
        label_gender.setText("Gender");
        jPanel1.add(label_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 60, -1));
        jPanel1.add(text_field_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 241, 30));

        text_field_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_field_ageActionPerformed(evt);
            }
        });
        jPanel1.add(text_field_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 241, 30));
        jPanel1.add(text_field_country, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 241, 30));

        button_clear.setForeground(new java.awt.Color(153, 0, 0));
        button_clear.setText("Clear");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });
        jPanel1.add(button_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 73, -1));

        button_register.setForeground(new java.awt.Color(153, 0, 0));
        button_register.setText("Register");
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });
        jPanel1.add(button_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 80, -1));

        button_update.setForeground(new java.awt.Color(153, 0, 0));
        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });
        jPanel1.add(button_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 73, -1));

        button_delete.setForeground(new java.awt.Color(153, 0, 0));
        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(button_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 70, -1));

        label_title.setFont(new java.awt.Font("DIN Condensed", 1, 36)); // NOI18N
        label_title.setForeground(new java.awt.Color(255, 255, 255));
        label_title.setText("Enter client details");
        jPanel1.add(label_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setForeground(new java.awt.Color(102, 0, 0));

        table_records.setBackground(new java.awt.Color(153, 0, 0));
        table_records.setForeground(new java.awt.Color(255, 255, 255));
        table_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Gender", "Country", "Age", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_records.getTableHeader().setResizingAllowed(false);
        table_records.getTableHeader().setReorderingAllowed(false);
        table_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_recordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_records);
        if (table_records.getColumnModel().getColumnCount() > 0) {
            table_records.getColumnModel().getColumn(0).setResizable(false);
            table_records.getColumnModel().getColumn(1).setResizable(false);
            table_records.getColumnModel().getColumn(2).setResizable(false);
            table_records.getColumnModel().getColumn(3).setResizable(false);
            table_records.getColumnModel().getColumn(4).setResizable(false);
            table_records.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 590, 260));

        button_refresh.setForeground(new java.awt.Color(153, 0, 0));
        button_refresh.setText("Refresh");
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });
        jPanel2.add(button_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 73, -1));

        button_back.setForeground(new java.awt.Color(153, 0, 0));
        button_back.setText("Back");
        button_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backActionPerformed(evt);
            }
        });
        jPanel2.add(button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 73, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        text_field_contact.setText( "" );
        text_field_country.setText( "" );
        text_field_email.setText( "" );
        text_field_age.setText( "" );
        text_field_name.setText( "" );
        button_group_gender.clearSelection();
    }//GEN-LAST:event_button_clearActionPerformed
    
    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        try {
            Application.g_app.GetDB().AddClient( new Client( 
                    text_field_name.getText(), 
                    text_field_email.getText(), 
                    text_field_country.getText(), 
                    text_field_contact.getText(), 
                    Integer.parseInt( text_field_age.getText() ), 
                    GetSelectedGender()  
                )
            );
            
            RefreshRecordTable();
            
            text_field_contact.setText("");
            text_field_country.setText("");
            text_field_email.setText("");
            text_field_age.setText("");
            text_field_name.setText("");
        }
        catch ( Exception e ) {
            System.out.println( "[ERROR] : " + e.getMessage() );
        }
    }//GEN-LAST:event_button_registerActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        try {
            if ( table_records.getSelectedRowCount() != 1  ) return;
            Client selected_client = GetSelectedClient();
            Client updated_client = new Client(
                    text_field_name.getText(),
                    text_field_email.getText(),
                    text_field_country.getText(),
                    text_field_contact.getText(),
                    Integer.parseInt( text_field_age.getText() ),
                    GetSelectedGender()
            );
            updated_client.SetId( selected_client.GetId() );
            
            Application.g_app.GetDB().UpdateClient( updated_client );
            RefreshRecordTable();
        } catch ( Exception e ) {
            System.out.println( "[ERROR] : " + e );
        }


    }//GEN-LAST:event_button_updateActionPerformed

    private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
        RefreshRecordTable();
    }//GEN-LAST:event_button_refreshActionPerformed

    private void button_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backActionPerformed
        this.dispose();
        new Dashboard().setVisible( true );
    }//GEN-LAST:event_button_backActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        try {       
            Application.g_app.GetDB().RemoveClient( GetSelectedClient() );
            
            RefreshRecordTable();
            
            text_field_contact.setText("");
            text_field_country.setText("");
            text_field_email.setText("");
            text_field_age.setText("");
            text_field_name.setText("");
        }
        catch ( Exception e ) {
            System.out.println( "[ERROR] : " + e.getMessage() );
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void table_recordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_recordsMouseClicked
       LoadRecordsToTextFields();
    }//GEN-LAST:event_table_recordsMouseClicked

    private void text_field_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_field_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_field_ageActionPerformed
  
    private void LoadRecordsToTextFields() {
        Client selected_client = GetSelectedClient();
        
        text_field_name.setText( selected_client.GetName() );
        text_field_age.setText( String.valueOf( selected_client.GetAge() ) );
        text_field_country.setText( selected_client.GetCountry() );
        text_field_email.setText( selected_client.GetEmail() );
        text_field_contact.setText( selected_client.GetContact() );
        
        switch (selected_client.GetGender()) {
            case MALE -> radio_button_male.setSelected(true);
            case FEMALE -> radio_button_female.setSelected(true);
            default -> radio_button_other.setSelected(true);
        }
    }
    
    private void RefreshRecordTable() {
        
        DefaultTableModel tblmdel = (DefaultTableModel) table_records.getModel();
        tblmdel.setRowCount(0);
        
        try {
            Client[] clients = Application.g_app.GetDB().GetClients();
            for ( Client client : clients ) {
                String tbdata[] = { 
                    String.valueOf( client.GetId() ),
                    client.GetName(), 
                    client.GetEmail(), 
                    client.GetGender().toString(), 
                    client.GetCountry(), 
                    String.valueOf( client.GetAge() ), 
                    client.GetContact() 
                };
                tblmdel.addRow( tbdata );
            }
        } catch ( Exception e ) {
            System.out.println( "[ERROR] : " + e );
        }

    }
    
    private Gender GetSelectedGender() {
        Gender gender = Gender.UNKNOWN;
        if ( button_group_gender.getSelection() != null ) {
            if ( button_group_gender.getSelection().getActionCommand().equals( Gender.MALE.toString() ) ) gender = Gender.MALE;
            else if ( button_group_gender.getSelection().getActionCommand().equals( Gender.FEMALE.toString() ) ) gender = Gender.FEMALE;
        }
        return gender;
    }

    private Client GetSelectedClient() {
        int selected_row_index = table_records.getSelectedRow();
        
        int c_id = Integer.parseInt( table_records.getModel().getValueAt( selected_row_index, 0 ).toString() );
        String c_name = table_records.getModel().getValueAt( selected_row_index, 1 ).toString();
        String c_email = table_records.getModel().getValueAt( selected_row_index, 2 ).toString();
        String c_gender_str = table_records.getModel().getValueAt( selected_row_index, 3 ).toString();
        String c_country = table_records.getModel().getValueAt( selected_row_index, 4 ).toString();
        int c_age = Integer.parseInt( table_records.getModel().getValueAt( selected_row_index, 5 ).toString() );
        String c_contact = table_records.getModel().getValueAt( selected_row_index, 6 ).toString();

        Gender c_gender = Gender.UNKNOWN;
        if ( c_gender_str.equals( Gender.MALE.toString() ) ) c_gender = Gender.MALE;
        else if ( c_gender_str.equals( Gender.FEMALE.toString() ) ) c_gender = Gender.FEMALE;
        
        Client client = null; 
        try {
            client = new Client( c_name, c_email, c_country, c_contact, c_age, c_gender );
            client.SetId( c_id );
        } catch ( Exception e ) {
            System.out.println( "[ERROR] : " + e );
        }
        
        return client;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_back;
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_delete;
    private javax.swing.ButtonGroup button_group_gender;
    private javax.swing.JButton button_refresh;
    private javax.swing.JButton button_register;
    private javax.swing.JButton button_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_age;
    private javax.swing.JLabel label_contact;
    private javax.swing.JLabel label_country;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_title;
    private javax.swing.JRadioButton radio_button_female;
    private javax.swing.JRadioButton radio_button_male;
    private javax.swing.JRadioButton radio_button_other;
    private javax.swing.JTable table_records;
    private java.awt.TextField text_field_age;
    private java.awt.TextField text_field_contact;
    private java.awt.TextField text_field_country;
    private java.awt.TextField text_field_email;
    private java.awt.TextField text_field_name;
    // End of variables declaration//GEN-END:variables
}
